### ISSUE TITLE
Error: cloud-frontier-frontend-dev already exists.

### ISSUE THREAD

**Issue by BlueCanary-DM** [riskprofiler/CloudFrontier#26]
It seems the bucket I need is created twice using CloudFormation which gives me an error.

```
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - cloud-frontier-frontend-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - cloud-frontier-frontend-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - cloud-frontier-frontend-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - S3BucketFrontend
CloudFormation - CREATE_FAILED - AWS::S3::Bucket - S3BucketFrontend
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - cloud-frontier-frontend-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - cloud-frontier-frontend-dev
CloudFormation - DELETE_COMPLETE - AWS::S3::Bucket - S3BucketFrontend
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - cloud-frontier-frontend-dev
Serverless: Operation failed!
Serverless: View the full error output: https://eu-west-3.console.aws.amazon.com/cloudformation/home?region=eu-west-3#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-west-3%3A990417434658%3Astack%2Fcloud-frontier-frontend-dev%2F0eeb5d40-d9a1-11eb-b25f-0a6b74c6c6e4

  Serverless Error ---------------------------------------

  An error occurred: S3BucketFrontend - cloud-frontier-frontend-dev already exists.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.1
     Framework Version:         1.83.3 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

cat: can't open 'frontend/temp-frontend-output': No such file or directory
rm: can't remove 'frontend/temp-frontend-output': No such file or directory
Front-end deplyed!

Deployment is complete! Visit https:// to get started.
```

**Comment by faheel** [comment]
I think the actual problem is that the S3 bucket names are the same for everyone who deploys the stack since they don't contain something unique (such as the AWS account ID to which the stack is being deployed).

Adding your AWS account ID in the S3 bucket names to make them unique should work.

```diff
-   S3BucketFrontend: cloud-frontier-frontend-${opt:stage, 'dev'}
+   S3BucketFrontend: cloud-frontier-frontend-#{AWS::AccountId}-${opt:stage, 'dev'}
```

**Comment by BlueCanary-DM** [comment]
Hi, thanks for the quick pull request. However, I get the error `InvalidBucketName: The specified bucket is not valid.`now.

```
Stack Outputs
ServerlessDeploymentBucketName: cloud-frontier-frontend-serverlessdeploymentbuck-15ox64bwphbj6
FrontendDomain: d3kovxk8rjbpp.cloudfront.net

S3 Sync: Syncing directories and S3 prefixes...

  Invalid Bucket Name ------------------------------------

  InvalidBucketName: The specified bucket is not valid.
      at Request.extractError (/cloud-frontier/node_modules/aws-sdk/lib/services/s3.js:714:35)
      at Request.callListeners (/cloud-frontier/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/cloud-frontier/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/cloud-frontier/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/cloud-frontier/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/cloud-frontier/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /cloud-frontier/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/cloud-frontier/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/cloud-frontier/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/cloud-frontier/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/cloud-frontier/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/cloud-frontier/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/cloud-frontier/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/cloud-frontier/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /cloud-frontier/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/cloud-frontier/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/cloud-frontier/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/cloud-frontier/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/cloud-frontier/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/cloud-frontier/node_modules/aws-sdk/lib/event_listeners.js:336:13)
      at IncomingMessage.emit (events.js:387:35)
      at IncomingMessage.emit (domain.js:470:12)
      at endReadableNT (internal/streams/readable.js:1317:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by faheel** [comment]
Have you installed all the dev dependencies mentioned in `package.json` (using `npm i -D`)?

If yes, and the error still persists, you can replace the `#{AWS::AccountId}` part in the bucket name with any string of your choice. That should definitely work.

**Comment by BlueCanary-DM** [comment]
I'm using the Docker container, so I assume everything is installed as it should be. I'll try the other approach

**Comment by BlueCanary-DM** [comment]
Seems it's working now, however I can't reach the url. Any idea how to reach it ?

```
AccessDeniedAccess DeniedT69DSX4Y3GYNGQCE4ETEXRccxi8uQ/vFZ3VioBhmt7KTGoJbxm/ASYVZOuC+cQN+S/KDbvz9xeLwuqBedqWNDoLwvZY=
```
